### ISSUE TITLE
Liste évolutions groupes libres rentrée 2017

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-admin-panel#159]
Issues détaillées des différentes évolutions :
- [x] Accès à la liste des groupes libres pour le profil Élèves : issue #78
- [x] Enrichissement des données affichées sur la liste des groupes libres : issue #34 
- [x] Possibilité de rendre privé un groupe libre lors de sa création / édition : issue #76 
- [x] Possibilité de faire une demande d'inscription à groupe : issue #76 
- [x] Possibilité de gérer une demande d'inscription à un groupe par l'administrateur : issue #77 
- [x] Possibilité d'ajouter des membres à un groupe libre en fonction de leur établissement / de leur profil / des regroupements existants : issue #136

**Comment by HuguesGithub** [comment]
- [ ] Possibilité de rendre privé un groupe libre lors de sa création / édition : issue #76
- - - [ ] Modification de l'interface
- - - [ ] Modification de l'API
- - - [ ] Modification de la table

**Comment by HuguesGithub** [comment]
- [ ] Enrichissement des données affichées sur la liste des groupes libres : issue #34
   - [ ] Nom de l'administrateur du groupe libre, affiché dans une nouvelle colonne
   - [ ] Si possible nom de l'établissement de l'administrateur du groupe libre, affiché dans une nouvelle colonne
   - [ ] Bulle avec le nombre de demandes d'inscription faites par les utilisateurs pour les groupes libres privés, et à traiter par l'administrateur de l'établissement, affichée dans la colonne nombre de membres du groupe
   - [ ] Statut indiquant :
      - [ ] le rôle de l'utilisateur connecté par rapport à chacun des groupes libres privés ou publics : membre ou administrateur
      - [ ] le traitement d'une demande d'inscription à un groupe libre privé par l'utilisateur demandeur : en attente / refusée. Tant qu'une demande n'est pas traitée par l'administrateur, c'est le statut "en attente" qui est affiché. Une demande d'inscription validée entraîne le changement de rôle de l'utilisateur pour ce groupe : il devient "membre". Lorsqu'une demande est refusée par l'administrateur, alors c'est le statut "refusée" qui reste affichée pour l'utilisateur demandeur
   - [ ] Une icône de type clé ou cadenas signalant devant leur nom les groupes libres privés
   - [x] Affichage en vert et en-tête de la liste des groupes libres les groupes libres de(s) l'établissement(s) de l'utilisateur connecté

**Comment by HuguesGithub** [comment]
Le nom de l'établissement ne peut pas être affiché pour le moment, la donnée n'est pas fournie.
Le statut "Membre" ne peut pas être affiché pour le moment. Sur l'interface des groupes libres, l'information n'est pas disponible. Il est nécessaire de faire une requête pour chaque groupe libre pour récupérer la liste des membres et la comparer au user courant. Très lourd si beaucoup de groupes. Il serait préférable d'avoir la liste des groupes_libres auquel est rattaché l'utilisateur, avec son statut...

**Comment by HuguesGithub** [comment]
- [ ] Possibilité de faire une demande d'inscription à groupe : issue #76 
  - [x] Un utilisateur non membre d'un groupe privé ne peut pas accéder à la liste des membres
  - [ ] Un utilisateur non membre d'un groupe privé peut faire une demande pour rejoindre le groupe.
